### ISSUE TITLE
PDFCredentials Plugin is blocking modoboa-installer from completing

### ISSUE THREAD

**Issue by almereyda** [modoboa/modoboa-pdfcredentials#2]
In https://github.com/modoboa/modoboa-installer/issues/36 we learned the PDFCredentials plugin is blocking the `modoboa-installer` from finishing.

I am mirroring the traceback here, in case the originating issue is closed:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/management/commands/load_initial_data.py", line 31, in handle
    admin.set_password("password")
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/models.py", line 164, in set_password
    "PasswordUpdated", self, raw_value, self.pk is None
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/events.py", line 90, in raiseEvent
    callback(*args, **kwargs)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_pdfcredentials/modo_extension.py", line 38, in password_updated
    init_storage_dir()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_pdfcredentials/lib.py", line 26, in init_storage_dir
    "PDF documents (%s)") % inst
modoboa.lib.exceptions.InternalError: Failed to create the directory that will contain PDF documents ([Errno 2] No such file or directory: '/var/lib/modoboa/pdf_crendentials')

python manage.py load_initial_data  failed, check your configuration
```

**Comment by tonioo** [comment]
As explained in the original issue, we're facing a "race condition". One possible solution (which applies to this plugin) could be to limit document generation to SimpleUsers accounts (and maybe DomainAdmins). Doing so, it would not block the deploy because only one super administrator is created.
